services:
  scheduler:
    build: .
    volumes:
      - .:/app
      - data_volume:/app/data
      - plots_volume:/app/plots
    env_file:
      - .env
    command: ["python", "scheduler.py"]
    restart: always

  dashboard:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - data_volume:/app/data
    env_file:
      - .env
    command: ["python", "dashboard.py"]
    restart: always

  streamer:
    build: .
    volumes:
      - .:/app
      - data_volume:/app/data
      - plots_volume:/app/plots
    env_file:
      - .env
    command: ["python", "services/streamer.py"]
    restart: always

  bist-scanner:
    build: .
    volumes:
      - .:/app
      - data_volume:/app/data
      - plots_volume:/app/plots
    env_file:
      - .env
    command: ["python", "services/bist_scanner.py"]
    restart: always

  test:
    build: .
    volumes:
      - .:/app
    command: ["python", "-m", "unittest", "discover", "tests"]

volumes:
  data_volume:
  plots_volume:
